name: kaggle-competitions
channels:
  - conda-forge
  - defaults
  - pytorch
platforms:
  - linux-64
dependencies:
  - python=3.10.10
  - poetry=1.4.*
  - mamba
  - conda-lock
  - ipykernel
  - nb_conda_kernels

  # PyTorch GPU installs
  # Manage these through conda as it's officially recommended by PyTorch, and
  # installing through Poetry looks like a pain
  # Note the versions are selected for use with Cuda ver. 11.4
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cudatoolkit=11.3
