name: kaggle-competitions
channels:
  - conda-forge
  - defaults
  - pytorch
platforms:
  - osx-64
dependencies:
  - python=3.10.10
  - poetry=1.4.*
  - mamba
  - ipykernel
  - nb_conda_kernels
  - jupyter
  - jupyter_contrib_nbextensions
  - pre-commit

